import { useState } from 'react';
import VisionHUD from './VisionHUD';
import { offlineStatus } from '../utils/offline';

export default function LandingPage({audioEnabled,contextMode,onToggleAudio,setContextMode}) {
  const [active,setActive]=useState(false),[cache,setCache]=useState('First setup needs internet. Check the offline cache before disconnecting.');
  if(active)return <VisionHUD audioEnabled={audioEnabled} contextMode={contextMode} onToggleAudio={onToggleAudio} setContextMode={setContextMode} onStopDemo={()=>setActive(false)} />;
  return <main className="start-shell">
    <header className="start-header"><b>SAARTHEYE</b><a href="https://github.com/MaybeSomeone-arc18/saartheye-ai" target="_blank" rel="noreferrer">Source code</a></header>
    <section className="start-hero"><p className="start-eyebrow">Accessible navigation research · browser prototype</p><h1>Objects in view.<br/>Cues you can hear.</h1><p className="start-lead">Local object detection, left/right stereo cues and optional vibration. A small experiment in phone-based spatial assistance.</p><button className="start-launch" onClick={()=>setActive(true)}>Start camera demo</button><p className="start-safety">Not a safety device or a replacement for a cane. Not tested with blind users. Try only in a supervised, clear indoor space.</p></section>
    <section className="start-grid" aria-label="What the prototype does"><article><span>01</span><h2>See locally</h2><p>TensorFlow.js COCO-SSD lite detects supported objects on the device. WebGL where available, CPU fallback. No YOLO or NPU claims.</p></article><article><span>02</span><h2>Follow the box</h2><p>Same-class matching, smoothed boxes and timed box growth. This is an approach proxy, not distance, physical speed or collision prediction.</p></article><article><span>03</span><h2>Hear the cue</h2><p>One prioritized left/right cue at a time. Social mode softens stable-person cues, while growing tracks can still warn. Vibration is optional.</p></article></section>
    <section className="start-facts"><div><h2>Proof before promises.</h2><p>The demo shows completed detections per second and inference p50/p95. These are real timings from your browser, not camera-to-sound latency or a phone benchmark.</p></div><div><h3>Private by design, narrow in scope</h3><p>The app does not implement camera recording or frame uploads. It detects 80 trained classes only. No detection does not mean a clear path.</p><h3>Offline after setup, when verified</h3><p>Production assets and model weights are cached by a service worker. Browser storage can be evicted. Installation does not make this native Android.</p><button onClick={async()=>{const s=await offlineStatus();setCache(s.ready?'Offline assets verified. Test app close/restart in airplane mode on your phone.':s.message);}}>Check offline readiness</button><p className="start-cache" role="status">{cache}</p></div></section>
    <footer className="start-footer"><p>Previously submitted to the Bengaluru city round in August 2026. This is a pre-existing prototype.</p><p>Finale proposal: a scoped new native Android pipeline and device measurements, subject to organizer rules on prebuilt code.</p><p>React · TensorFlow.js · COCO-SSD · Web Audio · MIT project</p></footer>
  </main>;
}
